name: Download & Upload to Release

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:    
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v5

      - name: 安装 Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: 安装依赖
        run: pip install requests

      - name: Run script
        run: python setting/download.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 生成版本号
        id: tag
        run: echo "tag=v$(date +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Upload soft
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          body: "自动构建"
          files: |
            soft/*

      - name: GH commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          file_pattern: "*.bat"